//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PaymentSystemWeb.PaymentSystemWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUserOfficerCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserSubscriberCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserSubscriberOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertSubscriberOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateInvoicePayOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInvoiceAllUnpaidOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInvoicePaidOperationCompleted;
        
        private System.Threading.SendOrPostCallback CloseSubscriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllSubscriberTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllSubscriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInvoiceAllUnpaidTotalAmountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::PaymentSystemWeb.Properties.Settings.Default.PaymentSystemWeb_PaymentSystemWebService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUserOfficerCheckCompletedEventHandler GetUserOfficerCheckCompleted;
        
        /// <remarks/>
        public event GetUserSubscriberCheckCompletedEventHandler GetUserSubscriberCheckCompleted;
        
        /// <remarks/>
        public event GetUserSubscriberCompletedEventHandler GetUserSubscriberCompleted;
        
        /// <remarks/>
        public event InsertSubscriberCompletedEventHandler InsertSubscriberCompleted;
        
        /// <remarks/>
        public event UpdateInvoicePayCompletedEventHandler UpdateInvoicePayCompleted;
        
        /// <remarks/>
        public event GetInvoiceAllUnpaidCompletedEventHandler GetInvoiceAllUnpaidCompleted;
        
        /// <remarks/>
        public event GetInvoicePaidCompletedEventHandler GetInvoicePaidCompleted;
        
        /// <remarks/>
        public event CloseSubscriptionCompletedEventHandler CloseSubscriptionCompleted;
        
        /// <remarks/>
        public event GetAllSubscriberTypeCompletedEventHandler GetAllSubscriberTypeCompleted;
        
        /// <remarks/>
        public event GetAllSubscriptionCompletedEventHandler GetAllSubscriptionCompleted;
        
        /// <remarks/>
        public event GetInvoiceAllUnpaidTotalAmountCompletedEventHandler GetInvoiceAllUnpaidTotalAmountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserOfficerCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OfficerCheckResponse GetUserOfficerCheck(OfficerCheckRequest request) {
            object[] results = this.Invoke("GetUserOfficerCheck", new object[] {
                        request});
            return ((OfficerCheckResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserOfficerCheckAsync(OfficerCheckRequest request) {
            this.GetUserOfficerCheckAsync(request, null);
        }
        
        /// <remarks/>
        public void GetUserOfficerCheckAsync(OfficerCheckRequest request, object userState) {
            if ((this.GetUserOfficerCheckOperationCompleted == null)) {
                this.GetUserOfficerCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserOfficerCheckOperationCompleted);
            }
            this.InvokeAsync("GetUserOfficerCheck", new object[] {
                        request}, this.GetUserOfficerCheckOperationCompleted, userState);
        }
        
        private void OnGetUserOfficerCheckOperationCompleted(object arg) {
            if ((this.GetUserOfficerCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserOfficerCheckCompleted(this, new GetUserOfficerCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserSubscriberCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SubscriberCheckResponse GetUserSubscriberCheck(SubscriberCheckRequest request) {
            object[] results = this.Invoke("GetUserSubscriberCheck", new object[] {
                        request});
            return ((SubscriberCheckResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserSubscriberCheckAsync(SubscriberCheckRequest request) {
            this.GetUserSubscriberCheckAsync(request, null);
        }
        
        /// <remarks/>
        public void GetUserSubscriberCheckAsync(SubscriberCheckRequest request, object userState) {
            if ((this.GetUserSubscriberCheckOperationCompleted == null)) {
                this.GetUserSubscriberCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserSubscriberCheckOperationCompleted);
            }
            this.InvokeAsync("GetUserSubscriberCheck", new object[] {
                        request}, this.GetUserSubscriberCheckOperationCompleted, userState);
        }
        
        private void OnGetUserSubscriberCheckOperationCompleted(object arg) {
            if ((this.GetUserSubscriberCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserSubscriberCheckCompleted(this, new GetUserSubscriberCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserSubscriber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SubscriberResponse GetUserSubscriber(SubscriberRequest request) {
            object[] results = this.Invoke("GetUserSubscriber", new object[] {
                        request});
            return ((SubscriberResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserSubscriberAsync(SubscriberRequest request) {
            this.GetUserSubscriberAsync(request, null);
        }
        
        /// <remarks/>
        public void GetUserSubscriberAsync(SubscriberRequest request, object userState) {
            if ((this.GetUserSubscriberOperationCompleted == null)) {
                this.GetUserSubscriberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserSubscriberOperationCompleted);
            }
            this.InvokeAsync("GetUserSubscriber", new object[] {
                        request}, this.GetUserSubscriberOperationCompleted, userState);
        }
        
        private void OnGetUserSubscriberOperationCompleted(object arg) {
            if ((this.GetUserSubscriberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserSubscriberCompleted(this, new GetUserSubscriberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertSubscriber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertSubscriber(InsertSubscriberRequest request) {
            object[] results = this.Invoke("InsertSubscriber", new object[] {
                        request});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertSubscriberAsync(InsertSubscriberRequest request) {
            this.InsertSubscriberAsync(request, null);
        }
        
        /// <remarks/>
        public void InsertSubscriberAsync(InsertSubscriberRequest request, object userState) {
            if ((this.InsertSubscriberOperationCompleted == null)) {
                this.InsertSubscriberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertSubscriberOperationCompleted);
            }
            this.InvokeAsync("InsertSubscriber", new object[] {
                        request}, this.InsertSubscriberOperationCompleted, userState);
        }
        
        private void OnInsertSubscriberOperationCompleted(object arg) {
            if ((this.InsertSubscriberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertSubscriberCompleted(this, new InsertSubscriberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateInvoicePay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateInvoicePay(UpdateInvoicePayRequest request) {
            object[] results = this.Invoke("UpdateInvoicePay", new object[] {
                        request});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateInvoicePayAsync(UpdateInvoicePayRequest request) {
            this.UpdateInvoicePayAsync(request, null);
        }
        
        /// <remarks/>
        public void UpdateInvoicePayAsync(UpdateInvoicePayRequest request, object userState) {
            if ((this.UpdateInvoicePayOperationCompleted == null)) {
                this.UpdateInvoicePayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateInvoicePayOperationCompleted);
            }
            this.InvokeAsync("UpdateInvoicePay", new object[] {
                        request}, this.UpdateInvoicePayOperationCompleted, userState);
        }
        
        private void OnUpdateInvoicePayOperationCompleted(object arg) {
            if ((this.UpdateInvoicePayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateInvoicePayCompleted(this, new UpdateInvoicePayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInvoiceAllUnpaid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InvoiceAllUnpaidResponse[] GetInvoiceAllUnpaid(int SubscriberId) {
            object[] results = this.Invoke("GetInvoiceAllUnpaid", new object[] {
                        SubscriberId});
            return ((InvoiceAllUnpaidResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInvoiceAllUnpaidAsync(int SubscriberId) {
            this.GetInvoiceAllUnpaidAsync(SubscriberId, null);
        }
        
        /// <remarks/>
        public void GetInvoiceAllUnpaidAsync(int SubscriberId, object userState) {
            if ((this.GetInvoiceAllUnpaidOperationCompleted == null)) {
                this.GetInvoiceAllUnpaidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInvoiceAllUnpaidOperationCompleted);
            }
            this.InvokeAsync("GetInvoiceAllUnpaid", new object[] {
                        SubscriberId}, this.GetInvoiceAllUnpaidOperationCompleted, userState);
        }
        
        private void OnGetInvoiceAllUnpaidOperationCompleted(object arg) {
            if ((this.GetInvoiceAllUnpaidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInvoiceAllUnpaidCompleted(this, new GetInvoiceAllUnpaidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInvoicePaid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InvoicePaidResponse[] GetInvoicePaid(int SubscriberId) {
            object[] results = this.Invoke("GetInvoicePaid", new object[] {
                        SubscriberId});
            return ((InvoicePaidResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInvoicePaidAsync(int SubscriberId) {
            this.GetInvoicePaidAsync(SubscriberId, null);
        }
        
        /// <remarks/>
        public void GetInvoicePaidAsync(int SubscriberId, object userState) {
            if ((this.GetInvoicePaidOperationCompleted == null)) {
                this.GetInvoicePaidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInvoicePaidOperationCompleted);
            }
            this.InvokeAsync("GetInvoicePaid", new object[] {
                        SubscriberId}, this.GetInvoicePaidOperationCompleted, userState);
        }
        
        private void OnGetInvoicePaidOperationCompleted(object arg) {
            if ((this.GetInvoicePaidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInvoicePaidCompleted(this, new GetInvoicePaidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CloseSubscription", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CloseSubscription(CloseSubscriptionRequest request) {
            object[] results = this.Invoke("CloseSubscription", new object[] {
                        request});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CloseSubscriptionAsync(CloseSubscriptionRequest request) {
            this.CloseSubscriptionAsync(request, null);
        }
        
        /// <remarks/>
        public void CloseSubscriptionAsync(CloseSubscriptionRequest request, object userState) {
            if ((this.CloseSubscriptionOperationCompleted == null)) {
                this.CloseSubscriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCloseSubscriptionOperationCompleted);
            }
            this.InvokeAsync("CloseSubscription", new object[] {
                        request}, this.CloseSubscriptionOperationCompleted, userState);
        }
        
        private void OnCloseSubscriptionOperationCompleted(object arg) {
            if ((this.CloseSubscriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CloseSubscriptionCompleted(this, new CloseSubscriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllSubscriberType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SubscriberTypeResponse[] GetAllSubscriberType() {
            object[] results = this.Invoke("GetAllSubscriberType", new object[0]);
            return ((SubscriberTypeResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllSubscriberTypeAsync() {
            this.GetAllSubscriberTypeAsync(null);
        }
        
        /// <remarks/>
        public void GetAllSubscriberTypeAsync(object userState) {
            if ((this.GetAllSubscriberTypeOperationCompleted == null)) {
                this.GetAllSubscriberTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllSubscriberTypeOperationCompleted);
            }
            this.InvokeAsync("GetAllSubscriberType", new object[0], this.GetAllSubscriberTypeOperationCompleted, userState);
        }
        
        private void OnGetAllSubscriberTypeOperationCompleted(object arg) {
            if ((this.GetAllSubscriberTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllSubscriberTypeCompleted(this, new GetAllSubscriberTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllSubscription", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SubscriptionResponse[] GetAllSubscription() {
            object[] results = this.Invoke("GetAllSubscription", new object[0]);
            return ((SubscriptionResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllSubscriptionAsync() {
            this.GetAllSubscriptionAsync(null);
        }
        
        /// <remarks/>
        public void GetAllSubscriptionAsync(object userState) {
            if ((this.GetAllSubscriptionOperationCompleted == null)) {
                this.GetAllSubscriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllSubscriptionOperationCompleted);
            }
            this.InvokeAsync("GetAllSubscription", new object[0], this.GetAllSubscriptionOperationCompleted, userState);
        }
        
        private void OnGetAllSubscriptionOperationCompleted(object arg) {
            if ((this.GetAllSubscriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllSubscriptionCompleted(this, new GetAllSubscriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInvoiceAllUnpaidTotalAmount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetInvoiceAllUnpaidTotalAmount(int SubscriberId) {
            object[] results = this.Invoke("GetInvoiceAllUnpaidTotalAmount", new object[] {
                        SubscriberId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetInvoiceAllUnpaidTotalAmountAsync(int SubscriberId) {
            this.GetInvoiceAllUnpaidTotalAmountAsync(SubscriberId, null);
        }
        
        /// <remarks/>
        public void GetInvoiceAllUnpaidTotalAmountAsync(int SubscriberId, object userState) {
            if ((this.GetInvoiceAllUnpaidTotalAmountOperationCompleted == null)) {
                this.GetInvoiceAllUnpaidTotalAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInvoiceAllUnpaidTotalAmountOperationCompleted);
            }
            this.InvokeAsync("GetInvoiceAllUnpaidTotalAmount", new object[] {
                        SubscriberId}, this.GetInvoiceAllUnpaidTotalAmountOperationCompleted, userState);
        }
        
        private void OnGetInvoiceAllUnpaidTotalAmountOperationCompleted(object arg) {
            if ((this.GetInvoiceAllUnpaidTotalAmountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInvoiceAllUnpaidTotalAmountCompleted(this, new GetInvoiceAllUnpaidTotalAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OfficerCheckRequest {
        
        private string userCodeField;
        
        private string userPasswordField;
        
        /// <remarks/>
        public string UserCode {
            get {
                return this.userCodeField;
            }
            set {
                this.userCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UserPassword {
            get {
                return this.userPasswordField;
            }
            set {
                this.userPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SubscriptionResponse {
        
        private int subscriptionIdField;
        
        private string subscriptionTypeField;
        
        private string finalPaymentDayField;
        
        private int depositField;
        
        private string insertUserField;
        
        private System.DateTime insertDateField;
        
        private string updateUserField;
        
        private System.Nullable<System.DateTime> updateDateField;
        
        /// <remarks/>
        public int SubscriptionId {
            get {
                return this.subscriptionIdField;
            }
            set {
                this.subscriptionIdField = value;
            }
        }
        
        /// <remarks/>
        public string SubscriptionType {
            get {
                return this.subscriptionTypeField;
            }
            set {
                this.subscriptionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FinalPaymentDay {
            get {
                return this.finalPaymentDayField;
            }
            set {
                this.finalPaymentDayField = value;
            }
        }
        
        /// <remarks/>
        public int Deposit {
            get {
                return this.depositField;
            }
            set {
                this.depositField = value;
            }
        }
        
        /// <remarks/>
        public string InsertUser {
            get {
                return this.insertUserField;
            }
            set {
                this.insertUserField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime InsertDate {
            get {
                return this.insertDateField;
            }
            set {
                this.insertDateField = value;
            }
        }
        
        /// <remarks/>
        public string UpdateUser {
            get {
                return this.updateUserField;
            }
            set {
                this.updateUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SubscriberTypeResponse {
        
        private int subscriberTypeIdField;
        
        private string typeNameField;
        
        /// <remarks/>
        public int SubscriberTypeId {
            get {
                return this.subscriberTypeIdField;
            }
            set {
                this.subscriberTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public string TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CloseSubscriptionRequest {
        
        private int subscriberIdField;
        
        private string updateUserField;
        
        /// <remarks/>
        public int SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        public string UpdateUser {
            get {
                return this.updateUserField;
            }
            set {
                this.updateUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InvoicePaidResponse {
        
        private int invoiceIdField;
        
        private int subscriberIdField;
        
        private string nameSurnameField;
        
        private int subscriptionIdField;
        
        private string subscriptionTypeField;
        
        private int invoiceAmountField;
        
        private System.DateTime cutOffDateField;
        
        private System.DateTime finalPaymentDateField;
        
        private string insertUserField;
        
        private System.DateTime insertDateField;
        
        private string updateUserField;
        
        private System.Nullable<System.DateTime> updateDateField;
        
        /// <remarks/>
        public int InvoiceId {
            get {
                return this.invoiceIdField;
            }
            set {
                this.invoiceIdField = value;
            }
        }
        
        /// <remarks/>
        public int SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        public string NameSurname {
            get {
                return this.nameSurnameField;
            }
            set {
                this.nameSurnameField = value;
            }
        }
        
        /// <remarks/>
        public int SubscriptionId {
            get {
                return this.subscriptionIdField;
            }
            set {
                this.subscriptionIdField = value;
            }
        }
        
        /// <remarks/>
        public string SubscriptionType {
            get {
                return this.subscriptionTypeField;
            }
            set {
                this.subscriptionTypeField = value;
            }
        }
        
        /// <remarks/>
        public int InvoiceAmount {
            get {
                return this.invoiceAmountField;
            }
            set {
                this.invoiceAmountField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CutOffDate {
            get {
                return this.cutOffDateField;
            }
            set {
                this.cutOffDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FinalPaymentDate {
            get {
                return this.finalPaymentDateField;
            }
            set {
                this.finalPaymentDateField = value;
            }
        }
        
        /// <remarks/>
        public string InsertUser {
            get {
                return this.insertUserField;
            }
            set {
                this.insertUserField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime InsertDate {
            get {
                return this.insertDateField;
            }
            set {
                this.insertDateField = value;
            }
        }
        
        /// <remarks/>
        public string UpdateUser {
            get {
                return this.updateUserField;
            }
            set {
                this.updateUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InvoiceAllUnpaidResponse {
        
        private int invoiceIdField;
        
        private int subscriberIdField;
        
        private string nameSurnameField;
        
        private int subscriptionIdField;
        
        private string subscriptionTypeField;
        
        private int invoiceAmountField;
        
        private System.DateTime cutOffDateField;
        
        private System.DateTime finalPaymentDateField;
        
        private string insertUserField;
        
        private System.DateTime insertDateField;
        
        private string updateUserField;
        
        private System.Nullable<System.DateTime> updateDateField;
        
        /// <remarks/>
        public int InvoiceId {
            get {
                return this.invoiceIdField;
            }
            set {
                this.invoiceIdField = value;
            }
        }
        
        /// <remarks/>
        public int SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        public string NameSurname {
            get {
                return this.nameSurnameField;
            }
            set {
                this.nameSurnameField = value;
            }
        }
        
        /// <remarks/>
        public int SubscriptionId {
            get {
                return this.subscriptionIdField;
            }
            set {
                this.subscriptionIdField = value;
            }
        }
        
        /// <remarks/>
        public string SubscriptionType {
            get {
                return this.subscriptionTypeField;
            }
            set {
                this.subscriptionTypeField = value;
            }
        }
        
        /// <remarks/>
        public int InvoiceAmount {
            get {
                return this.invoiceAmountField;
            }
            set {
                this.invoiceAmountField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CutOffDate {
            get {
                return this.cutOffDateField;
            }
            set {
                this.cutOffDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FinalPaymentDate {
            get {
                return this.finalPaymentDateField;
            }
            set {
                this.finalPaymentDateField = value;
            }
        }
        
        /// <remarks/>
        public string InsertUser {
            get {
                return this.insertUserField;
            }
            set {
                this.insertUserField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime InsertDate {
            get {
                return this.insertDateField;
            }
            set {
                this.insertDateField = value;
            }
        }
        
        /// <remarks/>
        public string UpdateUser {
            get {
                return this.updateUserField;
            }
            set {
                this.updateUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateInvoicePayRequest {
        
        private int invoiceIdField;
        
        private string updateUserField;
        
        /// <remarks/>
        public int InvoiceId {
            get {
                return this.invoiceIdField;
            }
            set {
                this.invoiceIdField = value;
            }
        }
        
        /// <remarks/>
        public string UpdateUser {
            get {
                return this.updateUserField;
            }
            set {
                this.updateUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertSubscriberRequest {
        
        private int subscriberTypeIdField;
        
        private string identificationTaxNumberField;
        
        private string userPasswordField;
        
        private string nameField;
        
        private string surnameField;
        
        private int subscriptionIdField;
        
        private string insertUserField;
        
        /// <remarks/>
        public int SubscriberTypeId {
            get {
                return this.subscriberTypeIdField;
            }
            set {
                this.subscriberTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public string IdentificationTaxNumber {
            get {
                return this.identificationTaxNumberField;
            }
            set {
                this.identificationTaxNumberField = value;
            }
        }
        
        /// <remarks/>
        public string UserPassword {
            get {
                return this.userPasswordField;
            }
            set {
                this.userPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public int SubscriptionId {
            get {
                return this.subscriptionIdField;
            }
            set {
                this.subscriptionIdField = value;
            }
        }
        
        /// <remarks/>
        public string InsertUser {
            get {
                return this.insertUserField;
            }
            set {
                this.insertUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SubscriberResponse {
        
        private int subscriberIdField;
        
        private string nameField;
        
        private string surnameField;
        
        private int subscriberTypeIdField;
        
        private string subscriberTypeNameField;
        
        private string identificationTaxNumberField;
        
        private int subscriptionIdField;
        
        private string subscriptionTypeField;
        
        private bool activeField;
        
        private string insertUserField;
        
        private System.DateTime insertDateField;
        
        private string updateUserField;
        
        private System.Nullable<System.DateTime> updateDateField;
        
        /// <remarks/>
        public int SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public int SubscriberTypeId {
            get {
                return this.subscriberTypeIdField;
            }
            set {
                this.subscriberTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public string SubscriberTypeName {
            get {
                return this.subscriberTypeNameField;
            }
            set {
                this.subscriberTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public string IdentificationTaxNumber {
            get {
                return this.identificationTaxNumberField;
            }
            set {
                this.identificationTaxNumberField = value;
            }
        }
        
        /// <remarks/>
        public int SubscriptionId {
            get {
                return this.subscriptionIdField;
            }
            set {
                this.subscriptionIdField = value;
            }
        }
        
        /// <remarks/>
        public string SubscriptionType {
            get {
                return this.subscriptionTypeField;
            }
            set {
                this.subscriptionTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public string InsertUser {
            get {
                return this.insertUserField;
            }
            set {
                this.insertUserField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime InsertDate {
            get {
                return this.insertDateField;
            }
            set {
                this.insertDateField = value;
            }
        }
        
        /// <remarks/>
        public string UpdateUser {
            get {
                return this.updateUserField;
            }
            set {
                this.updateUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SubscriberRequest {
        
        private string identificationTaxNumberField;
        
        /// <remarks/>
        public string IdentificationTaxNumber {
            get {
                return this.identificationTaxNumberField;
            }
            set {
                this.identificationTaxNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SubscriberCheckResponse {
        
        private int subscriberIdField;
        
        private string nameField;
        
        private string surnameField;
        
        private int subscriberTypeIdField;
        
        private string identificationTaxNumberField;
        
        private int subscriptionIdField;
        
        private string insertUserField;
        
        private System.DateTime insertDateField;
        
        private string updateUserField;
        
        private System.Nullable<System.DateTime> updateDateField;
        
        /// <remarks/>
        public int SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public int SubscriberTypeId {
            get {
                return this.subscriberTypeIdField;
            }
            set {
                this.subscriberTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public string IdentificationTaxNumber {
            get {
                return this.identificationTaxNumberField;
            }
            set {
                this.identificationTaxNumberField = value;
            }
        }
        
        /// <remarks/>
        public int SubscriptionId {
            get {
                return this.subscriptionIdField;
            }
            set {
                this.subscriptionIdField = value;
            }
        }
        
        /// <remarks/>
        public string InsertUser {
            get {
                return this.insertUserField;
            }
            set {
                this.insertUserField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime InsertDate {
            get {
                return this.insertDateField;
            }
            set {
                this.insertDateField = value;
            }
        }
        
        /// <remarks/>
        public string UpdateUser {
            get {
                return this.updateUserField;
            }
            set {
                this.updateUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SubscriberCheckRequest {
        
        private string identificationTaxNumberField;
        
        private string userPasswordField;
        
        private int subscriberTypeIdField;
        
        /// <remarks/>
        public string IdentificationTaxNumber {
            get {
                return this.identificationTaxNumberField;
            }
            set {
                this.identificationTaxNumberField = value;
            }
        }
        
        /// <remarks/>
        public string UserPassword {
            get {
                return this.userPasswordField;
            }
            set {
                this.userPasswordField = value;
            }
        }
        
        /// <remarks/>
        public int SubscriberTypeId {
            get {
                return this.subscriberTypeIdField;
            }
            set {
                this.subscriberTypeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OfficerCheckResponse {
        
        private int officerIdField;
        
        private string userCodeField;
        
        private string nameField;
        
        private string surnameField;
        
        private string insertUserField;
        
        private System.DateTime insertDateField;
        
        private string updateUserField;
        
        private System.Nullable<System.DateTime> updateDateField;
        
        /// <remarks/>
        public int OfficerId {
            get {
                return this.officerIdField;
            }
            set {
                this.officerIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserCode {
            get {
                return this.userCodeField;
            }
            set {
                this.userCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public string InsertUser {
            get {
                return this.insertUserField;
            }
            set {
                this.insertUserField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime InsertDate {
            get {
                return this.insertDateField;
            }
            set {
                this.insertDateField = value;
            }
        }
        
        /// <remarks/>
        public string UpdateUser {
            get {
                return this.updateUserField;
            }
            set {
                this.updateUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetUserOfficerCheckCompletedEventHandler(object sender, GetUserOfficerCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserOfficerCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserOfficerCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OfficerCheckResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OfficerCheckResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetUserSubscriberCheckCompletedEventHandler(object sender, GetUserSubscriberCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserSubscriberCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserSubscriberCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubscriberCheckResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubscriberCheckResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetUserSubscriberCompletedEventHandler(object sender, GetUserSubscriberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserSubscriberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserSubscriberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubscriberResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubscriberResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InsertSubscriberCompletedEventHandler(object sender, InsertSubscriberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertSubscriberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertSubscriberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateInvoicePayCompletedEventHandler(object sender, UpdateInvoicePayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateInvoicePayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateInvoicePayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetInvoiceAllUnpaidCompletedEventHandler(object sender, GetInvoiceAllUnpaidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInvoiceAllUnpaidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInvoiceAllUnpaidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InvoiceAllUnpaidResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InvoiceAllUnpaidResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetInvoicePaidCompletedEventHandler(object sender, GetInvoicePaidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInvoicePaidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInvoicePaidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InvoicePaidResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InvoicePaidResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CloseSubscriptionCompletedEventHandler(object sender, CloseSubscriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CloseSubscriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CloseSubscriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAllSubscriberTypeCompletedEventHandler(object sender, GetAllSubscriberTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllSubscriberTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllSubscriberTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubscriberTypeResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubscriberTypeResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAllSubscriptionCompletedEventHandler(object sender, GetAllSubscriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllSubscriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllSubscriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubscriptionResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubscriptionResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetInvoiceAllUnpaidTotalAmountCompletedEventHandler(object sender, GetInvoiceAllUnpaidTotalAmountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInvoiceAllUnpaidTotalAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInvoiceAllUnpaidTotalAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591